### ISSUE TITLE
Porting Suzuki maps

### ISSUE THREAD

**Issue by AlKu84** [sapphire-bt/lcn2kai-decompress#1]
Good day! For my region, the latest version of Nissan maps was released in 2017. There are Suzuki maps that were updated in 2021. Please take a look, the files are located here: https://drive.google.com/file/d/1CiIHmJys2aFOPUD7t9rSlXjLNAeI4hh6/view?usp=sharing 
Is it possible to repack for Nissan?

**Comment by sapphire-bt** [comment]
> Is it possible to repack for Nissan?

Maybe, but not with my script; it only decompresses, and I have no plans to implement compression.
